name: phpmyadmin
version: 2.0.4
appVersion: 4.8.5
description: phpMyAdmin is an mysql administration frontend
keywords:
- mariadb
- mysql
- phpmyadmin
home: https://www.phpmyadmin.net/
icon: https://www.phpmyadmin.net/static/images/logo.png?2ccd9afd557e
sources:
- https://github.com/bitnami/bitnami-docker-phpmyadmin
maintainers:
- name: Bitnami
  email: containers@bitnami.com
engine: gotpl
